// @generated by ethos-monolith from Ethos source

pub enum Input {
    Record(Entry),
    Subscribe(Layer),
    Unsubscribe(SubscriptionHandle),
}

pub enum Output {
    Recorded(EntryIdentifier),
    Subscribed(SubscriptionHandle),
    Unsubscribed(SubscriptionHandle),
}

pub enum Refusal {
    AdmissionRejected(AdmissionRefusal),
    UnknownSubscription(SubscriptionHandle),
}

pub enum Stream {
    RecordChange(RecordEvent),
}

pub enum Layer {
    Spirit,
    Intent,
    Vision,
}

pub struct Description(pub String);

pub struct EntryIdentifier(pub String);

pub struct SubscriptionHandle(pub i64);

pub struct Entry {
    pub layer: Layer,
    pub description: Description,
}

pub enum AdmissionRefusal {
    Duplicate,
    InvalidRequest,
}

pub enum RecordEvent {
    RecordRecorded(EntryIdentifier),
}
