use std::{
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicUsize, Ordering},
};

use ethos_monolith::{
    build::{BuildError, GeneratedArtifact, GeneratedArtifactOperations},
    generate::{
        ComponentGeneration, ComponentGenerationOperations, ETHOS_GENERATED_MARKER,
        GeneratedComponent, GeneratedComponentOperations, GenerationError,
    },
};

static TEMPORARY_DIRECTORY_SEQUENCE: AtomicUsize = AtomicUsize::new(0);

fn temporary_directory(test_name: &str) -> PathBuf {
    let sequence = TEMPORARY_DIRECTORY_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!(
        "ethos-monolith-{test_name}-{}-{sequence}",
        std::process::id()
    ));
    fs::create_dir_all(&path).expect("create isolated test directory");
    path
}

fn interface_source(type_name: &str) -> String {
    format!(
        "Interface.{{0 1 0}}\n[]\n{{\n  [Accept.{type_name}]\n  [Accepted.{type_name}]\n  [Rejected.{type_name}]\n  [Changed.{type_name}]\n  [{type_name}.String]\n}}\n"
    )
}

fn signal_interface_source(type_name: &str) -> String {
    interface_source(type_name).replacen("[]\n", "Channel.{Fixture 7 3}\n[]\n", 1)
}

fn write_component_sources(source_directory: &Path) {
    fs::create_dir_all(source_directory).expect("create source directory");
    for (file_name, source) in [
        ("signal.ethos", signal_interface_source("SignalMessage")),
        ("nexus.ethos", interface_source("NexusMessage")),
        ("sema.ethos", interface_source("SemaMessage")),
    ] {
        fs::write(source_directory.join(file_name), source).expect("write Interface source");
    }
}

#[test]
fn missing_artifact_is_stale() {
    let path = PathBuf::from("ethos-monolith-test-missing.rs");
    let error = GeneratedArtifact::new(&path, "generated")
        .assert_matches_existing()
        .expect_err("missing artifact is stale");

    assert!(matches!(&error, BuildError::StaleGeneratedArtifact { path: found } if found == &path));
}

#[test]
fn generated_component_exposes_three_artifacts() {
    let signal = GeneratedArtifact::new("signal.rs", "// signal");
    let nexus = GeneratedArtifact::new("nexus.rs", "// nexus");
    let sema = GeneratedArtifact::new("sema.rs", "// sema");
    let component = GeneratedComponent::new(signal.clone(), nexus.clone(), sema.clone());

    assert_eq!(component.signal(), &signal);
    assert_eq!(component.nexus(), &nexus);
    assert_eq!(component.sema(), &sema);
}

#[test]
fn component_generation_derives_expected_paths() {
    let generation = ComponentGeneration::new("/src/my-component", "/out/my-component");

    assert_eq!(
        generation.signal_source_path(),
        PathBuf::from("/src/my-component/signal.ethos")
    );
    assert_eq!(
        generation.nexus_source_path(),
        PathBuf::from("/src/my-component/nexus.ethos")
    );
    assert_eq!(
        generation.sema_source_path(),
        PathBuf::from("/src/my-component/sema.ethos")
    );
    assert_eq!(
        generation.signal_output_path(),
        PathBuf::from("/out/my-component/signal.rs")
    );
    assert_eq!(
        generation.nexus_output_path(),
        PathBuf::from("/out/my-component/nexus.rs")
    );
    assert_eq!(
        generation.sema_output_path(),
        PathBuf::from("/out/my-component/sema.rs")
    );
}

#[test]
fn ethos_generated_marker_is_present() {
    assert!(ETHOS_GENERATED_MARKER.starts_with("// @generated by ethos-monolith"));
}

#[test]
fn generation_emits_the_three_checked_interface_modules() {
    let temporary = temporary_directory("emits-three-modules");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_component_sources(&source_directory);

    let generation = ComponentGeneration::new(&source_directory, &output_directory);
    let generated = generation.generate().expect("generate component modules");

    for (artifact, type_name) in [
        (generated.signal(), "SignalMessage"),
        (generated.nexus(), "NexusMessage"),
        (generated.sema(), "SemaMessage"),
    ] {
        artifact
            .assert_matches_existing()
            .expect("generated artifact is installed");
        assert!(
            artifact.content().starts_with(ETHOS_GENERATED_MARKER),
            "every generated artifact is marked"
        );
        assert!(
            artifact
                .content()
                .contains(&format!("pub struct {type_name}(pub String);")),
            "the output reflects the source declaration"
        );
        syn::parse_file(artifact.content()).expect("emitted text parses as Rust");
        assert!(
            std::process::Command::new("rustfmt")
                .args(["--edition", "2024", "--check"])
                .arg(artifact.path())
                .status()
                .expect("invoke rustfmt for generated artifact")
                .success(),
            "generated artifact is already rustfmt canonical"
        );
    }
    assert!(
        generated
            .signal()
            .content()
            .contains("pub enum FixtureWire {}")
    );
    assert!(
        generated
            .signal()
            .content()
            .contains("pub type FixtureRequest = Operation;")
    );

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn invalid_source_fails_before_any_output_is_installed() {
    let temporary = temporary_directory("invalid-source-preserves-output");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_component_sources(&source_directory);
    fs::write(
        source_directory.join("nexus.ethos"),
        "Interface.{0 1 0} [] {}",
    )
    .expect("write malformed nexus source");
    fs::create_dir_all(&output_directory).expect("create output directory");
    for file_name in ["signal.rs", "nexus.rs", "sema.rs"] {
        fs::write(
            output_directory.join(file_name),
            "// existing committed artifact\n",
        )
        .expect("seed existing output");
    }

    let generation = ComponentGeneration::new(&source_directory, &output_directory);
    let error = generation
        .generate()
        .expect_err("invalid source is rejected");

    assert!(
        matches!(error, GenerationError::Interface { path, .. } if path == source_directory.join("nexus.ethos"))
    );
    for file_name in ["signal.rs", "nexus.rs", "sema.rs"] {
        assert_eq!(
            fs::read_to_string(output_directory.join(file_name)).expect("read existing output"),
            "// existing committed artifact\n",
            "invalid input must not partially install output"
        );
    }

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn generation_emits_vector_aliases_and_empty_interface_modules() {
    let temporary = temporary_directory("vector-and-empty-interface");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_component_sources(&source_directory);
    fs::write(
        source_directory.join("signal.ethos"),
        "Interface.{0 1 0}\nChannel.{Fixture 7 3}\n[]\n{\n  []\n  []\n  []\n  []\n  [Path.String PathSet.Vector<Path>]\n}\n",
    )
    .expect("write vector-bearing signal source");
    let empty_interface = "Interface.{0 1 0}\n[]\n{\n  []\n  []\n  []\n  []\n  []\n}\n";
    fs::write(source_directory.join("nexus.ethos"), empty_interface)
        .expect("write empty nexus source");
    fs::write(source_directory.join("sema.ethos"), empty_interface)
        .expect("write empty sema source");

    let generated = ComponentGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("generate vector and empty interfaces");

    assert!(
        generated
            .signal()
            .content()
            .contains("pub struct PathSet(pub Vec<Path>);"),
        "Vector<T> is a concrete Vec<T> carrier in emitted Rust"
    );
    for artifact in [generated.nexus(), generated.sema()] {
        assert!(artifact.content().contains("pub enum Input {}"));
        assert!(artifact.content().contains("pub enum Output {}"));
        syn::parse_file(artifact.content()).expect("empty interface emission is Rust");
    }

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn generation_emits_struct_fields_in_rust_snake_case() {
    let temporary = temporary_directory("snake-case-fields");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_component_sources(&source_directory);
    fs::write(
        source_directory.join("signal.ethos"),
        "Interface.{0 1 0}\nChannel.{Fixture 7 3}\n[]\n{\n  [Configure.Configuration]\n  [Configured.Configuration]\n  []\n  []\n  [StorePath.String OrdinarySocketPath.String MetaSocketPath.String Configuration.{StorePath OrdinarySocketPath MetaSocketPath}]\n}\n",
    )
    .expect("write multiword-field signal source");

    let generated = ComponentGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("generate multiword struct fields");

    for field in ["store_path", "ordinary_socket_path", "meta_socket_path"] {
        assert!(
            generated
                .signal()
                .content()
                .contains(&format!("pub {field}: ")),
            "generated field uses Rust snake case: {field}"
        );
    }

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn generation_emits_comparable_wire_marker_and_named_struct_textual_heads() {
    let temporary = temporary_directory("wire-marker-and-struct-heads");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_component_sources(&source_directory);
    fs::write(
        source_directory.join("signal.ethos"),
        "Interface.{0 1 0}\nChannel.{Fixture 7 3}\n[]\n{\n  [Register.PathLock]\n  [PathLockRegistered.PathLockRegistered PathLockRegistrationRejected.PathLockRegistrationRejected]\n  []\n  []\n  [PathLockName.String PathLockPath.String PathLockPaths.Vector<PathLockPath> PathLockDescription.String PathLockRegistrationRefusal.[DuplicateActiveName.PathLockName] PathLock.{PathLockName PathLockPaths PathLockDescription} PathLockRegistered.{PathLock} PathLockRegistrationRejected.{PathLock PathLockRegistrationRefusal}]\n}\n",
    )
    .expect("write named-head signal source");

    let generated = ComponentGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("generate named-head signal source");
    let signal = generated.signal().content();

    assert!(
        signal.contains("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum FixtureWire {}"),
        "the marker meets BoundExchangeFrame structural bounds"
    );
    assert!(
        signal.contains("\"PathLock.{}\"")
            && signal.contains("<Self as ::dotos::DotosBodyEncode>::to_dotos_body(self)"),
        "a concrete named payload retains its ruled Type.{{...}} head"
    );
    assert!(
        signal.contains("\"PathLockName.{}\"")
            && signal.contains("<Self as EthosValueEncoding>::to_ethos_value(self)"),
        "a concrete named scalar retains its ruled Type.value head"
    );
    assert!(
        signal.contains("EthosValueEncoding::to_ethos_value(&self.path_lock_name)"),
        "a named struct omits a nested nominal scalar head"
    );
    assert!(
        signal.contains("EthosValueEncoding::to_ethos_value(&self.path_lock_paths)"),
        "a named vector field emits its elements without nominal heads"
    );
    assert!(
        signal.contains("::dotos::Delimiter::SquareBracket.wrap(self.iter().map(EthosValueEncoding::to_ethos_value))"),
        "a vector projects each nominal element as its underlying value"
    );
    assert!(
        signal.contains("\"PathLockRegistered.{}\"")
            && signal
                .contains("<PathLock as ::dotos::DotosBodyEncode>::to_dotos_body(&self.path_lock)"),
        "a one-field named wrapper flattens its nested record under one outer body"
    );
    assert!(
        signal.contains("<PathLockRegistrationRefusal as EthosValueDecoding>::from_ethos_value"),
        "an enum-bearing reply decodes its nested refusal without a nominal head"
    );
    assert!(
        !signal.contains("return match variant {\n                other =>"),
        "a data-only closed enum rejects an atom directly instead of emitting a single-binding match"
    );

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}
