use std::{
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicUsize, Ordering},
};

use ethos_monolith::{
    build::{BuildError, GeneratedArtifact, GeneratedArtifactOperations},
    generate::{
        ETHOS_GENERATED_MARKER, GeneratedSignal, GeneratedSignalOperations, GenerationError,
        SignalGeneration, SignalGenerationOperations,
    },
};

static TEMPORARY_DIRECTORY_SEQUENCE: AtomicUsize = AtomicUsize::new(0);

fn temporary_directory(test_name: &str) -> PathBuf {
    let sequence = TEMPORARY_DIRECTORY_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!(
        "ethos-monolith-{test_name}-{}-{sequence}",
        std::process::id()
    ));
    fs::create_dir_all(&path).expect("create isolated test directory");
    path
}

fn signal_interface_source(type_name: &str) -> String {
    format!(
        "Interface.{{0 1 0}}\nChannel.{{Fixture 7 3}}\n[]\n{{\n  [Accept.{type_name}]\n  [Accepted.{type_name}]\n  [Rejected.{type_name}]\n  [Changed.{type_name}]\n  [{type_name}.String]\n}}\n"
    )
}

fn write_signal_source(source_directory: &Path, source: &str) {
    fs::create_dir_all(source_directory).expect("create source directory");
    fs::write(source_directory.join("signal.ethos"), source).expect("write signal source");
}

#[test]
fn missing_artifact_is_stale() {
    let path = PathBuf::from("ethos-monolith-test-missing.rs");
    let error = GeneratedArtifact::new(&path, "generated")
        .assert_matches_existing()
        .expect_err("missing artifact is stale");

    assert!(matches!(&error, BuildError::StaleGeneratedArtifact { path: found } if found == &path));
}

#[test]
fn generated_signal_exposes_its_artifact() {
    let signal = GeneratedArtifact::new("signal.rs", "// signal");
    let generated = GeneratedSignal::new(signal.clone());

    assert_eq!(generated.signal(), &signal);
}

#[test]
fn signal_generation_derives_expected_paths() {
    let generation = SignalGeneration::new("/src/my-signal", "/out/my-signal");

    assert_eq!(
        generation.signal_source_path(),
        PathBuf::from("/src/my-signal/signal.ethos")
    );
    assert_eq!(
        generation.signal_output_path(),
        PathBuf::from("/out/my-signal/signal.rs")
    );
}

#[test]
fn ethos_generated_marker_is_present() {
    assert!(ETHOS_GENERATED_MARKER.starts_with("// @generated by ethos-monolith"));
}

#[test]
fn generation_emits_a_checked_signal_module() {
    let temporary = temporary_directory("emits-signal-module");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_signal_source(&source_directory, &signal_interface_source("SignalMessage"));

    let generated = SignalGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("generate signal module");
    let artifact = generated.signal();

    artifact
        .assert_matches_existing()
        .expect("generated artifact is installed");
    assert!(artifact.content().starts_with(ETHOS_GENERATED_MARKER));
    assert!(
        artifact
            .content()
            .contains("pub struct SignalMessage(pub String);")
    );
    assert!(artifact.content().contains("pub enum FixtureWire {}"));
    assert!(
        artifact
            .content()
            .contains("pub type FixtureRequest = Operation;")
    );
    syn::parse_file(artifact.content()).expect("emitted text parses as Rust");
    assert!(
        std::process::Command::new("rustfmt")
            .args(["--edition", "2024", "--check"])
            .arg(artifact.path())
            .status()
            .expect("invoke rustfmt for generated artifact")
            .success(),
        "generated artifact is already rustfmt canonical"
    );

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn channel_is_required_and_an_invalid_source_preserves_existing_output() {
    let temporary = temporary_directory("missing-channel-preserves-output");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_signal_source(
        &source_directory,
        "Interface.{0 1 0}\n[]\n{\n  []\n  []\n  []\n  []\n  []\n}\n",
    );
    fs::create_dir_all(&output_directory).expect("create output directory");
    let output_path = output_directory.join("signal.rs");
    fs::write(&output_path, "// existing committed artifact\n").expect("seed existing output");

    let error = SignalGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect_err("signal without its channel is rejected");

    assert!(
        matches!(error, GenerationError::Interface { path, .. } if path == source_directory.join("signal.ethos"))
    );
    assert_eq!(
        fs::read_to_string(&output_path).expect("read existing output"),
        "// existing committed artifact\n"
    );

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn generation_emits_vector_aliases() {
    let temporary = temporary_directory("vector-alias");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_signal_source(
        &source_directory,
        "Interface.{0 1 0}\nChannel.{Fixture 7 3}\n[]\n{\n  []\n  []\n  []\n  []\n  [Path.String PathSet.Vector<Path>]\n}\n",
    );

    let generated = SignalGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("generate vector-bearing signal");

    assert!(
        generated
            .signal()
            .content()
            .contains("pub struct PathSet(pub Vec<Path>);")
    );

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn generation_emits_struct_fields_in_rust_snake_case() {
    let temporary = temporary_directory("snake-case-fields");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_signal_source(
        &source_directory,
        "Interface.{0 1 0}\nChannel.{Fixture 7 3}\n[]\n{\n  [Configure.Configuration]\n  [Configured.Configuration]\n  []\n  []\n  [StorePath.String OrdinarySocketPath.String MetaSocketPath.String Configuration.{StorePath OrdinarySocketPath MetaSocketPath}]\n}\n",
    );

    let generated = SignalGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("generate multiword struct fields");

    for field in ["store_path", "ordinary_socket_path", "meta_socket_path"] {
        assert!(
            generated
                .signal()
                .content()
                .contains(&format!("pub {field}: ")),
            "generated field uses Rust snake case: {field}"
        );
    }

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn generation_emits_datom_structural_projection_without_legacy_dotos_codecs() {
    let temporary = temporary_directory("wire-marker-and-struct-heads");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_signal_source(
        &source_directory,
        "Interface.{0 1 0}\nChannel.{Fixture 7 3}\n[]\n{\n  [Register.PathLock]\n  [PathLockRegistered.PathLockRegistered PathLockRegistrationRejected.PathLockRegistrationRejected]\n  []\n  []\n  [PathLockName.String PathLockPath.String PathLockPaths.Vector<PathLockPath> PathLockDescription.String PathLockRegistrationRefusal.[DuplicateActiveName.PathLockName] PathLock.{PathLockName PathLockPaths PathLockDescription} PathLockRegistered.{PathLock} PathLockRegistrationRejected.{PathLock PathLockRegistrationRefusal}]\n}\n",
    );

    let generated = SignalGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("generate named-head signal source");
    let signal = generated.signal().content();

    assert!(
        signal.contains("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum FixtureWire {}")
    );
    assert!(signal.contains("trait EthosDatomRecord"));
    assert!(signal.contains("impl ::datom::DatomRealizing for PathLock"));
    assert!(signal.contains("impl ::datom::DatomTextualizing for PathLock"));
    assert!(signal.contains("impl ::datom::DatomRealizing for Operation"));
    assert!(signal.contains("impl ::datom::DatomTextualizing for Operation"));
    assert!(signal.contains("impl DatomRoot for Operation {}"));
    assert!(signal.contains("Shape::DottedBraced"));
    assert!(!signal.contains("::dotos::"));

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}

#[test]
fn generation_realizes_the_approved_orchestrate_contract_tree() {
    let temporary = temporary_directory("orchestrate-contract");
    let source_directory = temporary.join("ethos");
    let output_directory = temporary.join("rust");
    write_signal_source(
        &source_directory,
        "Interface.{0 2 0}\nChannel.{Orchestrate 1 5}\n[]\n{\n  [Lock.LockRequest Release.LockId Observe.ObserveSelection]\n  [Locked.Lock LockRejected.LockRejection Released.Lock ReleaseRejected.ReleaseRejection Observed.Observation]\n  []\n  []\n  [LockName.String FlowId.String LockPath.String LockPaths.Vector<LockPath> LockReason.String LockRequest.{LockName FlowId LockPaths LockReason} LockId.Integer Lock.{LockId LockName FlowId LockPaths LockReason} DuplicateName.Lock LockOverlap.{LockPath Lock} LockRejection.[DuplicateName.Lock PathOverlap.LockOverlap] ReleaseRejection.[UnknownLockId] ObserveSelection.[Locks.LocksSelection] LocksSelection.[Current] Locks.Vector<Lock> LockSnapshot.{Locks} Observation.[Locks.LockSnapshot]]\n}\n",
    );

    let generated = SignalGeneration::new(&source_directory, &output_directory)
        .generate()
        .expect("approved contract generates");
    let signal = generated.signal().content();

    for type_name in [
        "LockRequest",
        "Lock",
        "LockRejection",
        "ReleaseRejection",
        "ObserveSelection",
        "LocksSelection",
        "LockSnapshot",
        "Observation",
    ] {
        assert!(
            signal.contains(&format!(
                "pub {} {type_name}",
                if type_name.ends_with("Request")
                    || type_name == "Lock"
                    || type_name.ends_with("Snapshot")
                {
                    "struct"
                } else {
                    "enum"
                }
            )),
            "generated {type_name}"
        );
    }
    assert!(signal.contains("operation Lock(LockRequest)"));
    assert!(signal.contains("operation Release(LockId)"));
    assert!(signal.contains("operation Observe(ObserveSelection)"));
    assert!(signal.contains("Locked(Lock)"));
    assert!(signal.contains("Observed(Observation)"));
    assert!(signal.contains("WireRevision::new(NonZeroU16::new(5)"));
    assert!(!signal.contains("PathLock"));
    assert!(!signal.contains("Register("));

    fs::remove_dir_all(temporary).expect("remove isolated test directory");
}
