use std::path::PathBuf;

use ethos_rust::{
    build::{BuildError, GeneratedArtifact},
    generate::{ComponentGeneration, ETHOS_GENERATED_MARKER, GeneratedComponent},
};

#[test]
fn missing_artifact_is_stale() {
    let path = PathBuf::from("ethos-rust-test-missing.rs");
    let error = GeneratedArtifact::new(&path, "generated")
        .assert_matches_existing()
        .expect_err("missing artifact is stale");

    assert!(matches!(&error, BuildError::StaleGeneratedArtifact { path: found } if found == &path));
}

#[test]
fn generated_component_exposes_three_artifacts() {
    let signal = GeneratedArtifact::new("signal.rs", "// signal");
    let nexus = GeneratedArtifact::new("nexus.rs", "// nexus");
    let sema = GeneratedArtifact::new("sema.rs", "// sema");
    let component = GeneratedComponent::new(signal.clone(), nexus.clone(), sema.clone());

    assert_eq!(component.signal(), &signal);
    assert_eq!(component.nexus(), &nexus);
    assert_eq!(component.sema(), &sema);
}

#[test]
fn component_generation_derives_expected_paths() {
    let generation = ComponentGeneration::new("/src/my-component", "/out/my-component");

    assert_eq!(
        generation.signal_source_path(),
        PathBuf::from("/src/my-component/signal.ethos")
    );
    assert_eq!(
        generation.nexus_source_path(),
        PathBuf::from("/src/my-component/nexus.ethos")
    );
    assert_eq!(
        generation.sema_source_path(),
        PathBuf::from("/src/my-component/sema.ethos")
    );
    assert_eq!(
        generation.signal_output_path(),
        PathBuf::from("/out/my-component/signal.rs")
    );
    assert_eq!(
        generation.nexus_output_path(),
        PathBuf::from("/out/my-component/nexus.rs")
    );
    assert_eq!(
        generation.sema_output_path(),
        PathBuf::from("/out/my-component/sema.rs")
    );
}

#[test]
fn ethos_generated_marker_is_present() {
    assert!(ETHOS_GENERATED_MARKER.starts_with("// @generated by ethos-rust"));
}
