//! Generation surface: Ethos text in, component Rust artifacts out.
//!
//! A caller binds an Ethos source directory and an output directory to a
//! `ComponentGeneration`, then drives generation to receive a
//! `GeneratedComponent` carrying three `GeneratedArtifact` values —
//! `signal.rs`, `nexus.rs`, and `sema.rs`.
//!
//! Consumers commit the emitted Rust; they do not depend on this crate.
//! The generator implementation is supplied by a later phase; this module
//! owns the emission boundary and its types.

use std::path::{Path, PathBuf};

use crate::build::{GeneratedArtifact, GeneratedArtifactOperations};

/// Marker placed as the first line of every Rust artifact emitted by
/// ethos-monolith.
pub const ETHOS_GENERATED_MARKER: &str = "// @generated by ethos-monolith from Ethos source\n";

/// One complete component generation request.
///
/// Binds a directory of Ethos source files to a target output directory.
/// The three Ethos files are read by name: `signal.ethos`, `nexus.ethos`,
/// and `sema.ethos`. The generated Rust is written as `signal.rs`,
/// `nexus.rs`, and `sema.rs` under the output directory.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ComponentGeneration {
    source_directory: PathBuf,
    output_directory: PathBuf,
}

/// Operations for binding source and output directories to generated paths.
pub trait ComponentGenerationOperations {
    /// Bind the source and output directories for one component.
    fn new(source_directory: impl Into<PathBuf>, output_directory: impl Into<PathBuf>) -> Self
    where
        Self: Sized;

    /// Directory containing the component's Ethos source files.
    fn source_directory(&self) -> &Path;

    /// Directory where the three generated Rust artifacts will be written.
    fn output_directory(&self) -> &Path;

    /// Expected path of the signal Ethos source file.
    fn signal_source_path(&self) -> PathBuf;

    /// Expected path of the nexus Ethos source file.
    fn nexus_source_path(&self) -> PathBuf;

    /// Expected path of the sema Ethos source file.
    fn sema_source_path(&self) -> PathBuf;

    /// Expected path of the generated signal Rust artifact.
    fn signal_output_path(&self) -> PathBuf;

    /// Expected path of the generated nexus Rust artifact.
    fn nexus_output_path(&self) -> PathBuf;

    /// Expected path of the generated sema Rust artifact.
    fn sema_output_path(&self) -> PathBuf;
}

impl ComponentGenerationOperations for ComponentGeneration {
    fn new(source_directory: impl Into<PathBuf>, output_directory: impl Into<PathBuf>) -> Self {
        Self {
            source_directory: source_directory.into(),
            output_directory: output_directory.into(),
        }
    }

    fn source_directory(&self) -> &Path {
        &self.source_directory
    }

    fn output_directory(&self) -> &Path {
        &self.output_directory
    }

    fn signal_source_path(&self) -> PathBuf {
        self.source_directory.join("signal.ethos")
    }

    fn nexus_source_path(&self) -> PathBuf {
        self.source_directory.join("nexus.ethos")
    }

    fn sema_source_path(&self) -> PathBuf {
        self.source_directory.join("sema.ethos")
    }

    fn signal_output_path(&self) -> PathBuf {
        self.output_directory.join("signal.rs")
    }

    fn nexus_output_path(&self) -> PathBuf {
        self.output_directory.join("nexus.rs")
    }

    fn sema_output_path(&self) -> PathBuf {
        self.output_directory.join("sema.rs")
    }
}

/// Three Rust artifacts for one generated component.
///
/// Every component generation produces exactly these three artifacts.
/// Consumers commit all three; they are checked as a unit.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedComponent {
    signal: GeneratedArtifact,
    nexus: GeneratedArtifact,
    sema: GeneratedArtifact,
}

/// Operations for accessing and checking a generated component's artifacts.
pub trait GeneratedComponentOperations {
    /// Bind explicit artifact projections for the three component files.
    fn new(signal: GeneratedArtifact, nexus: GeneratedArtifact, sema: GeneratedArtifact) -> Self
    where
        Self: Sized;

    /// Generated `signal.rs` artifact.
    fn signal(&self) -> &GeneratedArtifact;

    /// Generated `nexus.rs` artifact.
    fn nexus(&self) -> &GeneratedArtifact;

    /// Generated `sema.rs` artifact.
    fn sema(&self) -> &GeneratedArtifact;

    /// Verify that all three artifacts match their checked-in content.
    fn assert_all_match_existing(&self) -> Result<(), crate::build::BuildError>;
}

impl GeneratedComponentOperations for GeneratedComponent {
    fn new(signal: GeneratedArtifact, nexus: GeneratedArtifact, sema: GeneratedArtifact) -> Self {
        Self {
            signal,
            nexus,
            sema,
        }
    }

    fn signal(&self) -> &GeneratedArtifact {
        &self.signal
    }

    fn nexus(&self) -> &GeneratedArtifact {
        &self.nexus
    }

    fn sema(&self) -> &GeneratedArtifact {
        &self.sema
    }

    fn assert_all_match_existing(&self) -> Result<(), crate::build::BuildError> {
        self.signal.assert_matches_existing()?;
        self.nexus.assert_matches_existing()?;
        self.sema.assert_matches_existing()?;
        Ok(())
    }
}
