//! Signal generation surface: Ethos text in, one wire Rust artifact out.
//!
//! A caller binds a signal repository's Ethos source directory and Rust output
//! directory to a `SignalGeneration`. It reads `signal.ethos` and writes
//! `signal.rs`. Consumers commit the emitted Rust; they do not depend on this
//! crate.

use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use protos::{Realize, SourceText};

use crate::build::{GeneratedArtifact, GeneratedArtifactOperations};
use crate::fixture::{InterfaceFault, InterfaceText, SignalArtifactProjecting};

trait RustFormatting {
    fn rustfmt(self) -> Result<Self, String>
    where
        Self: Sized;
}

impl RustFormatting for GeneratedArtifact {
    fn rustfmt(self) -> Result<Self, String> {
        let mut child = Command::new("rustfmt")
            .args(["--edition", "2024", "--emit", "stdout"])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|source| source.to_string())?;
        child
            .stdin
            .as_mut()
            .ok_or_else(|| "rustfmt did not open standard input".to_owned())?
            .write_all(self.content().as_bytes())
            .map_err(|source| source.to_string())?;
        let output = child
            .wait_with_output()
            .map_err(|source| source.to_string())?;
        if !output.status.success() {
            return Err(String::from_utf8_lossy(&output.stderr).into_owned());
        }
        let content = String::from_utf8(output.stdout).map_err(|source| source.to_string())?;
        Ok(GeneratedArtifact::new(self.path().to_path_buf(), content))
    }
}

/// Marker placed as the first line of every Rust artifact emitted by
/// ethos-monolith.
pub const ETHOS_GENERATED_MARKER: &str = "// @generated by ethos-monolith from Ethos source\n";

/// One signal wire-generation request.
///
/// Binds the directory containing `signal.ethos` to the directory where
/// `signal.rs` is installed.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SignalGeneration {
    source_directory: PathBuf,
    output_directory: PathBuf,
}

/// Operations for binding the signal source and output directories.
pub trait SignalGenerationOperations {
    /// Bind the source and output directories for one signal repository.
    fn new(source_directory: impl Into<PathBuf>, output_directory: impl Into<PathBuf>) -> Self
    where
        Self: Sized;

    /// Directory containing `signal.ethos`.
    fn source_directory(&self) -> &Path;

    /// Directory where `signal.rs` is written.
    fn output_directory(&self) -> &Path;

    /// Expected path of the signal Ethos source file.
    fn signal_source_path(&self) -> PathBuf;

    /// Expected path of the generated signal Rust artifact.
    fn signal_output_path(&self) -> PathBuf;

    /// Realize the signal source and install its Rust projection.
    fn generate(&self) -> Result<GeneratedSignal, GenerationError>;
}

impl SignalGenerationOperations for SignalGeneration {
    fn new(source_directory: impl Into<PathBuf>, output_directory: impl Into<PathBuf>) -> Self {
        Self {
            source_directory: source_directory.into(),
            output_directory: output_directory.into(),
        }
    }

    fn source_directory(&self) -> &Path {
        &self.source_directory
    }

    fn output_directory(&self) -> &Path {
        &self.output_directory
    }

    fn signal_source_path(&self) -> PathBuf {
        self.source_directory.join("signal.ethos")
    }

    fn signal_output_path(&self) -> PathBuf {
        self.output_directory.join("signal.rs")
    }

    fn generate(&self) -> Result<GeneratedSignal, GenerationError> {
        let source_path = self.signal_source_path();
        let output_path = self.signal_output_path();
        let source =
            fs::read_to_string(&source_path).map_err(|source| GenerationError::ReadSource {
                path: source_path.clone(),
                source,
            })?;
        let interface = InterfaceText {
            source: SourceText(source),
        }
        .realize()
        .map_err(|source| GenerationError::Interface {
            path: source_path.clone(),
            source,
        })?;
        let artifact = interface
            .signal_rust_artifact(output_path.clone())
            .map_err(|source| GenerationError::Interface {
                path: source_path,
                source,
            })?;
        syn::parse_file(artifact.content()).map_err(|source| GenerationError::InvalidRust {
            path: output_path.clone(),
            detail: source.to_string(),
        })?;
        let artifact = artifact
            .rustfmt()
            .map_err(|detail| GenerationError::FormatRust {
                path: output_path,
                detail,
            })?;
        let pending_path = artifact.pending_path();
        artifact
            .write_to(&pending_path)
            .map_err(|source| GenerationError::WriteArtifact { source })?;
        fs::rename(&pending_path, artifact.path()).map_err(|source| {
            GenerationError::InstallArtifact {
                pending_path,
                path: artifact.path().to_path_buf(),
                source,
            }
        })?;
        Ok(GeneratedSignal::new(artifact))
    }
}

/// Failure while realizing or installing generated signal Rust.
#[derive(Debug, thiserror::Error)]
pub enum GenerationError {
    /// The canonical signal Ethos source path could not be read.
    #[error("read Ethos source {path:?}: {source}")]
    ReadSource {
        path: PathBuf,
        source: std::io::Error,
    },
    /// The source document does not satisfy the signal Interface dialect.
    #[error("realize Ethos source {path:?}: {source}")]
    Interface {
        path: PathBuf,
        source: InterfaceFault,
    },
    /// The complete projection is not syntactically valid Rust.
    #[error("generated Rust {path:?} is invalid: {detail}")]
    InvalidRust { path: PathBuf, detail: String },
    /// The canonical Rust formatter rejected a complete projection.
    #[error("format generated Rust {path:?}: {detail}")]
    FormatRust { path: PathBuf, detail: String },
    /// A pending generated artifact could not be written.
    #[error("write pending generated artifact: {source}")]
    WriteArtifact { source: crate::build::BuildError },
    /// A fully realized pending artifact could not replace its output path.
    #[error("install generated artifact from {pending_path:?} to {path:?}: {source}")]
    InstallArtifact {
        pending_path: PathBuf,
        path: PathBuf,
        source: std::io::Error,
    },
}

/// One Rust artifact generated for a signal wire consumer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedSignal {
    signal: GeneratedArtifact,
}

/// Operations for accessing and checking a generated signal artifact.
pub trait GeneratedSignalOperations {
    /// Bind the generated signal artifact.
    fn new(signal: GeneratedArtifact) -> Self
    where
        Self: Sized;

    /// Generated `signal.rs` artifact.
    fn signal(&self) -> &GeneratedArtifact;

    /// Verify the signal artifact matches its checked-in content.
    fn assert_matches_existing(&self) -> Result<(), crate::build::BuildError>;
}

impl GeneratedSignalOperations for GeneratedSignal {
    fn new(signal: GeneratedArtifact) -> Self {
        Self { signal }
    }

    fn signal(&self) -> &GeneratedArtifact {
        &self.signal
    }

    fn assert_matches_existing(&self) -> Result<(), crate::build::BuildError> {
        self.signal.assert_matches_existing()
    }
}
