//! Generation surface: Ethos text in, component Rust artifacts out.
//!
//! A caller binds an Ethos source directory and an output directory to a
//! `ComponentGeneration`, then drives generation to receive a
//! `GeneratedComponent` carrying three `GeneratedArtifact` values —
//! `signal.rs`, `nexus.rs`, and `sema.rs`.
//!
//! Consumers commit the emitted Rust; they do not depend on this crate.
//! The generator implementation is supplied by a later phase; this module
//! owns the emission boundary and its types.

use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use protos::{Realize, SourceText};

use crate::build::{GeneratedArtifact, GeneratedArtifactOperations};
use crate::fixture::{
    InterfaceFault, InterfaceText, RustArtifactProjecting, SignalArtifactProjecting,
};

trait RustFormatting {
    fn rustfmt(self) -> Result<Self, String>
    where
        Self: Sized;
}

impl RustFormatting for GeneratedArtifact {
    fn rustfmt(self) -> Result<Self, String> {
        let mut child = Command::new("rustfmt")
            .args(["--edition", "2024", "--emit", "stdout"])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|source| source.to_string())?;
        child
            .stdin
            .as_mut()
            .ok_or_else(|| "rustfmt did not open standard input".to_owned())?
            .write_all(self.content().as_bytes())
            .map_err(|source| source.to_string())?;
        let output = child
            .wait_with_output()
            .map_err(|source| source.to_string())?;
        if !output.status.success() {
            return Err(String::from_utf8_lossy(&output.stderr).into_owned());
        }
        let content = String::from_utf8(output.stdout).map_err(|source| source.to_string())?;
        Ok(GeneratedArtifact::new(self.path().to_path_buf(), content))
    }
}

/// Marker placed as the first line of every Rust artifact emitted by
/// ethos-monolith.
pub const ETHOS_GENERATED_MARKER: &str = "// @generated by ethos-monolith from Ethos source\n";

/// One complete component generation request.
///
/// Binds a directory of Ethos source files to a target output directory.
/// The three Ethos files are read by name: `signal.ethos`, `nexus.ethos`,
/// and `sema.ethos`. The generated Rust is written as `signal.rs`,
/// `nexus.rs`, and `sema.rs` under the output directory.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ComponentGeneration {
    source_directory: PathBuf,
    output_directory: PathBuf,
}

/// Operations for binding source and output directories to generated paths.
pub trait ComponentGenerationOperations {
    /// Bind the source and output directories for one component.
    fn new(source_directory: impl Into<PathBuf>, output_directory: impl Into<PathBuf>) -> Self
    where
        Self: Sized;

    /// Directory containing the component's Ethos source files.
    fn source_directory(&self) -> &Path;

    /// Directory where the three generated Rust artifacts will be written.
    fn output_directory(&self) -> &Path;

    /// Expected path of the signal Ethos source file.
    fn signal_source_path(&self) -> PathBuf;

    /// Expected path of the nexus Ethos source file.
    fn nexus_source_path(&self) -> PathBuf;

    /// Expected path of the sema Ethos source file.
    fn sema_source_path(&self) -> PathBuf;

    /// Expected path of the generated signal Rust artifact.
    fn signal_output_path(&self) -> PathBuf;

    /// Expected path of the generated nexus Rust artifact.
    fn nexus_output_path(&self) -> PathBuf;

    /// Expected path of the generated sema Rust artifact.
    fn sema_output_path(&self) -> PathBuf;

    /// Realize all six canonical paths and install their three Rust projections.
    fn generate(&self) -> Result<GeneratedComponent, GenerationError>;
}

impl ComponentGenerationOperations for ComponentGeneration {
    fn new(source_directory: impl Into<PathBuf>, output_directory: impl Into<PathBuf>) -> Self {
        Self {
            source_directory: source_directory.into(),
            output_directory: output_directory.into(),
        }
    }

    fn source_directory(&self) -> &Path {
        &self.source_directory
    }

    fn output_directory(&self) -> &Path {
        &self.output_directory
    }

    fn signal_source_path(&self) -> PathBuf {
        self.source_directory.join("signal.ethos")
    }

    fn nexus_source_path(&self) -> PathBuf {
        self.source_directory.join("nexus.ethos")
    }

    fn sema_source_path(&self) -> PathBuf {
        self.source_directory.join("sema.ethos")
    }

    fn signal_output_path(&self) -> PathBuf {
        self.output_directory.join("signal.rs")
    }

    fn nexus_output_path(&self) -> PathBuf {
        self.output_directory.join("nexus.rs")
    }

    fn sema_output_path(&self) -> PathBuf {
        self.output_directory.join("sema.rs")
    }

    fn generate(&self) -> Result<GeneratedComponent, GenerationError> {
        let artifact_from_source = |source_path: PathBuf,
                                    output_path: PathBuf,
                                    signal: bool|
         -> Result<GeneratedArtifact, GenerationError> {
            let source =
                fs::read_to_string(&source_path).map_err(|source| GenerationError::ReadSource {
                    path: source_path.clone(),
                    source,
                })?;
            let interface = InterfaceText {
                source: SourceText(source),
            }
            .realize()
            .map_err(|source| GenerationError::Interface {
                path: source_path.clone(),
                source,
            })?;
            let artifact = if signal {
                interface.signal_rust_artifact(output_path.clone())
            } else {
                interface.rust_artifact(output_path.clone())
            }
            .map_err(|source| GenerationError::Interface {
                path: source_path.clone(),
                source,
            })?;
            syn::parse_file(artifact.content()).map_err(|source| GenerationError::InvalidRust {
                path: output_path.clone(),
                detail: source.to_string(),
            })?;
            artifact
                .rustfmt()
                .map_err(|detail| GenerationError::FormatRust {
                    path: output_path,
                    detail,
                })
        };
        let signal =
            artifact_from_source(self.signal_source_path(), self.signal_output_path(), true)?;
        let nexus =
            artifact_from_source(self.nexus_source_path(), self.nexus_output_path(), false)?;
        let sema = artifact_from_source(self.sema_source_path(), self.sema_output_path(), false)?;
        let generated = GeneratedComponent::new(signal, nexus, sema);
        let artifacts = [generated.signal(), generated.nexus(), generated.sema()];
        let mut pending = Vec::new();
        for artifact in artifacts {
            let path = artifact.pending_path();
            if let Err(source) = artifact.write_to(&path) {
                for pending_path in pending {
                    let _ = fs::remove_file(pending_path);
                }
                return Err(GenerationError::WriteArtifact { source });
            }
            pending.push(path);
        }
        for artifact in artifacts {
            let pending_path = artifact.pending_path();
            fs::rename(&pending_path, artifact.path()).map_err(|source| {
                GenerationError::InstallArtifact {
                    pending_path,
                    path: artifact.path().to_path_buf(),
                    source,
                }
            })?;
        }
        Ok(generated)
    }
}

/// Failure while realizing or installing one component's generated Rust.
#[derive(Debug, thiserror::Error)]
pub enum GenerationError {
    /// A required canonical Ethos source path could not be read.
    #[error("read Ethos source {path:?}: {source}")]
    ReadSource {
        path: PathBuf,
        source: std::io::Error,
    },
    /// A source document does not satisfy the supported Ethos Interface dialect.
    #[error("realize Ethos source {path:?}: {source}")]
    Interface {
        path: PathBuf,
        source: InterfaceFault,
    },
    /// The complete projection is not syntactically valid Rust.
    #[error("generated Rust {path:?} is invalid: {detail}")]
    InvalidRust { path: PathBuf, detail: String },
    /// The canonical Rust formatter rejected a complete projection.
    #[error("format generated Rust {path:?}: {detail}")]
    FormatRust { path: PathBuf, detail: String },
    /// A pending generated artifact could not be written.
    #[error("write pending generated artifact: {source}")]
    WriteArtifact { source: crate::build::BuildError },
    /// A fully realized pending artifact could not replace its output path.
    #[error("install generated artifact from {pending_path:?} to {path:?}: {source}")]
    InstallArtifact {
        pending_path: PathBuf,
        path: PathBuf,
        source: std::io::Error,
    },
}

/// Three Rust artifacts for one generated component.
///
/// Every component generation produces exactly these three artifacts.
/// Consumers commit all three; they are checked as a unit.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedComponent {
    signal: GeneratedArtifact,
    nexus: GeneratedArtifact,
    sema: GeneratedArtifact,
}

/// Operations for accessing and checking a generated component's artifacts.
pub trait GeneratedComponentOperations {
    /// Bind explicit artifact projections for the three component files.
    fn new(signal: GeneratedArtifact, nexus: GeneratedArtifact, sema: GeneratedArtifact) -> Self
    where
        Self: Sized;

    /// Generated `signal.rs` artifact.
    fn signal(&self) -> &GeneratedArtifact;

    /// Generated `nexus.rs` artifact.
    fn nexus(&self) -> &GeneratedArtifact;

    /// Generated `sema.rs` artifact.
    fn sema(&self) -> &GeneratedArtifact;

    /// Verify that all three artifacts match their checked-in content.
    fn assert_all_match_existing(&self) -> Result<(), crate::build::BuildError>;
}

impl GeneratedComponentOperations for GeneratedComponent {
    fn new(signal: GeneratedArtifact, nexus: GeneratedArtifact, sema: GeneratedArtifact) -> Self {
        Self {
            signal,
            nexus,
            sema,
        }
    }

    fn signal(&self) -> &GeneratedArtifact {
        &self.signal
    }

    fn nexus(&self) -> &GeneratedArtifact {
        &self.nexus
    }

    fn sema(&self) -> &GeneratedArtifact {
        &self.sema
    }

    fn assert_all_match_existing(&self) -> Result<(), crate::build::BuildError> {
        self.signal.assert_matches_existing()?;
        self.nexus.assert_matches_existing()?;
        self.sema.assert_matches_existing()?;
        Ok(())
    }
}
